- name: setup master instance
  hosts: all
  remote_user: ubuntu
  become: yes
  become_method: sudo
  gather_facts: no

  tasks:
    - name: Update apt cache
      apt: 
        update_cache: yes

    - name: When both of these are in place, we'll run update so that apt-get will use the new repository
      apt:
        update_cache: yes

    - name: install dependencies
      apt:
        name:
          - nginx
          - php7.0-curl
          - php7.0-cli
          - php7.0-intl
          - php7.0-mbstring
          - php7.0-gd
          - php-imagick
          - php7.0-fpm
          - php7.0-xml
          - php7.0-zip
        state: present

    - name: update cache || equivalent of sudo apt-get update
      apt:
        update_cache: yes

    - name: set up
      shell: apt-get -y install software-properties-common && systemctl status php7.0-fpm.service

    - name: update
      apt:
        update_cache: yes

  pre_tasks:        
    - name: 'install php'
      raw: sudo apt-get -y install php